Repository xpxchxcx/SpeakEase, pull requests merged in 2023-02, with the labels that each got.

#7 Improve code quality and documentation
  .github/workflows/ci.yml
  .github/workflows/pylint.yml
  .pylintrc
  README.md
  analysis_video_pipeline/src/custom_nodes/dabble/movement.py
  analysis_video_pipeline/tests/test_node.py
  analysis_video_pipeline/tests/visualise.py
  doc/analysis_video_pipeline/src/custom_nodes/dabble/movement.html
  doc/analysis_video_pipeline/tests/test_node.html
  doc/analysis_video_pipeline/tests/visualise.html
  doc/helper.html
  doc/raw_transfer.html
  helper.py
  raw_transfer.py
Labels: documentation

#8 Fix GitHub workflow configuration
  .github/workflows/ci.yml
  .github/workflows/pylint.yml
  README.md
Labels: bug

#10 Enable statistics summary per detected individual
  .github/workflows/ci.yml
  .github/workflows/pylint.yml
  analysis_video_pipeline/pipeline_config.yml
  analysis_video_pipeline/src/custom_nodes/__init__.py
  analysis_video_pipeline/src/custom_nodes/configs/dabble/are_arms_folded.yml
  analysis_video_pipeline/src/custom_nodes/configs/dabble/debug.yml
  analysis_video_pipeline/src/custom_nodes/configs/dabble/is_leaning.yml
  analysis_video_pipeline/src/custom_nodes/configs/dabble/is_touching_face.yml
  analysis_video_pipeline/src/custom_nodes/configs/draw/stats.yml
  analysis_video_pipeline/src/custom_nodes/dabble/__init__.py
  analysis_video_pipeline/src/custom_nodes/dabble/are_arms_folded.py
  analysis_video_pipeline/src/custom_nodes/dabble/debug.py
  analysis_video_pipeline/src/custom_nodes/dabble/is_leaning.py
  analysis_video_pipeline/src/custom_nodes/dabble/is_touching_face.py
  analysis_video_pipeline/src/custom_nodes/dabble/tests/__init__.py
  analysis_video_pipeline/src/custom_nodes/dabble/tests/test_arms_folded.py
  analysis_video_pipeline/src/custom_nodes/dabble/tests/test_is_leaning.py
  analysis_video_pipeline/src/custom_nodes/dabble/tests/test_is_touching_face.py
  analysis_video_pipeline/src/custom_nodes/dabble/tests/test_utils.py
  analysis_video_pipeline/src/custom_nodes/dabble/utils.py
  analysis_video_pipeline/src/custom_nodes/draw/__init__.py
  analysis_video_pipeline/src/custom_nodes/draw/stats.py
  analysis_video_pipeline/src/custom_nodes/draw/utils.py
  analysis_video_pipeline/src/custom_nodes/visualise.py
  doc/analysis_video_pipeline/index.html
  doc/analysis_video_pipeline/src/custom_nodes/dabble/index.html
  doc/analysis_video_pipeline/src/custom_nodes/dabble/movement.html
  doc/analysis_video_pipeline/src/custom_nodes/index.html
  doc/analysis_video_pipeline/src/index.html
  doc/analysis_video_pipeline/tests/index.html
  doc/analysis_video_pipeline/tests/test_node.html
  doc/analysis_video_pipeline/tests/visualise.html
  doc/helper.html
  doc/index.html
  doc/raw_transfer.html
  legacy/helper.py
  legacy/movement.py
  legacy/movement.yml
  legacy/test.txt
  legacy/test_node.py
  program_flow.bat
  program_flow.sh
  raw_video_pipeline/pipeline_config.yml
Labels: enhancement

#13 Fix analysis input video size and draw output
  analysis_video_pipeline/pipeline_config.yml
  analysis_video_pipeline/src/custom_nodes/draw/stats.py
Labels: bug

#14 Fix input video size in pipeline config
  analysis_video_pipeline/pipeline_config.yml
  raw_video_pipeline/pipeline_config.yml
Labels: bug

#15 Update README.md
  README.md
Labels: documentation

#16 Update README.md
  README.md
Labels: documentation

#17 Fix documentation (minor)
  .github/workflows/pylint.yml
  analysis_video_pipeline/src/custom_nodes/dabble/are_arms_folded.py
  analysis_video_pipeline/src/custom_nodes/dabble/is_leaning.py
  analysis_video_pipeline/src/custom_nodes/dabble/tests/test_arms_folded.py
  analysis_video_pipeline/src/custom_nodes/dabble/tests/test_is_leaning.py
  analysis_video_pipeline/src/custom_nodes/dabble/tests/test_is_touching_face.py
  analysis_video_pipeline/src/custom_nodes/dabble/tests/test_utils.py
  analysis_video_pipeline/src/custom_nodes/draw/stats.py
  analysis_video_pipeline/src/custom_nodes/draw/utils.py
Labels: documentation

#19 Resize Logo to follow device size
  README.md
Labels: bug, documentation
